### ISSUE TITLE
Falta el endpoint para hacer el GET de la lista de favoritos de el usuario actual (1 solo usuario)

### ISSUE THREAD

**Issue by StefAranzazu** [Dans182/StarWars-REST-API#1]
![image](https://user-images.githubusercontent.com/84442570/167839025-2e3b397c-86d4-4cb0-8e63-04d26d0ff18e.png)

**Comment by Dans182** [comment]
Stef, no es este endpoint el que me pides?

![imagen](https://user-images.githubusercontent.com/97400328/168787276-fcc1e7c5-9a10-440e-9891-ca8564ec2719.png)

**Comment by StefAranzazu** [comment]
Mas o menos, porque al ejecutarlo me agrega un elemento vacío porque estás haciendo un db.session.add y db.session.commit.
